const Shipping = [ 
    {
    title:"SHIPPING",
    body:"WE OFFER COMPLIMENTARY GROUND SHIPPING VIA FEDEX OR UPS ON ALL U.S. ORDERS.  THE SHIPMENT WILL NORMALLY BE DELIVERED WITHIN 5 TO 7 BUSINESS DAYS. THREE DAY DELIVERY - $12 YOUR ORDER MUST REACH US BY 12:00 PM EST AND 3 DAY AIR MUST BE SELECTED IN CHECK-OUT. THE SHIPMENT WILL NORMALLY BE DELIVERED WITHIN THREE BUSINESS DAYS. EXPRESS/SECOND DAY DELIVERY - $25 YOUR ORDER MUST REACH US BY 12:00 PM EST AND 2ND DAY AIR MUST BE SELECTED IN CHECK-OUT. THE SHIPMENT WILL NORMALLY BE DELIVERED WITHIN TWO BUSINESS DAYS. OVERNIGHT DELIVERY - $30 YOUR ORDER MUST REACH US BY 12:00 PM EST AND OVERNIGHT SHIPPING MUST BE SELECTED IN CHECK-OUT.  THE SHIPMENT WILL NORMALLY BE DELIVERED THE FOLLOWING BUSINESS DAY. ONCE WE HAVE SHIPPED YOUR ORDER, WE WILL SEND YOU AN EMAIL WITH SHIPPING DETAILS AND A FEDEX OR UPS TRACKING NUMBER. FOLLOW THE LINK IN THE EMAIL TO CHECK THE ESTIMATED ARRIVAL OF YOUR ORDER. YOU, OR AN AUTHORIZED PERSON, MUST SIGN FOR YOUR ORDER UPON ARRIVAL. THIS ENSURES YOUR PURCHASES ARE SAFELY DELIVERED TO YOU. IF YOU ARE UNAVAILABLE WHEN YOUR PACKAGE ARRIVES, FEDEX OR UPS WILL LEAVE A RE-DELIVERY SLIP.WE CANNOT SHIP TO POST OFFICE BOXES, APO/FPO ADDRESSES, FREIGHT FORWARDERS, HOTEL OR MOTEL ADDRESS. WE CANNOT SHIP TO PUERTO RICO, GUAM AND ALL OTHER U.S. POSSESSIONS AND TERRITORIES SITUATED OUTSIDE NORTH AMERICA."
    },
    {
    title:"RETURNS",
    body:"SALE MERCHANDISE IS FINAL SALE. WE DO NOT OFFER RETURNS, EXCHANGES, OR STORE CREDIT ON PURCHASED SALE ITEMS. YOU MAY RETURN ANY NON-FINAL-SALE PRODUCT ORDERED ON THE TOMFORD.COM WEBSITE FOR REFUND WITHIN FOURTEEN (14) CALENDAR DAYS FROM THE DELIVERY DATE. RETURNED PRODUCTS MUST BE IN THEIR ORIGINAL CONDITION, UNUSED, UNWASHED, UNALTERED, AND IN THE SAME CONDITION IN WHICH IT WAS RECEIVED WITH ALL TAGS ATTACHED, AND IN THE ORIGINAL PACKAGING AND PLASTIC WRAP (INCLUDING, IF POSSIBLE, THE ORIGINAL DELIVERY BOX). THE ORIGINAL INVOICE MUST BE PROVIDED WITH ANY RETURN. UNDERWEAR IS FINAL SALE.  WE DO NOT OFFER RETURNS, EXCHANGES, OR STORE CREDIT ON PURCHASED UNDERWEAR ITEMS. TO RETURN A PRODUCT, LOGIN TO YOUR ACCOUNT TO REQUEST A RETURNS MERCHANDISE AUTHORIZATION (RMA) OR CONTACT CUSTOMER SERVICE AT ASSISTANCE@TOMFORDINTERNATIONAL.COM OR CALL 1-888-TOM-FORD. FOR MORE INFORMATION ON RETURNS PLEASE SEE TERMS AND CONDITIONS."
    },  
    {
    title:"EXCHANGES",
    body:"AT THIS TIME, TOMFORD.COM PURCHASES CANNOT BE EXCHANGED THROUGH TOMFORD.COM.  TOMFORD.COM ORDERS CAN INSTEAD BE BROUGHT TO A TOM FORD BOUTIQUE TO BE EXCHANGED OR RETURNED (TO THE ORIGINAL FORM OF PAYMENT OR A GIFT CARD). CERTAIN RESTRICTIONS APPLY TO ANY RETURN OR EXCHANGE, INCLUDING FOR ALTERED OR PERSONALIZED PRODUCTS, SALE AND OTHER NON-RETURNABLE PRODUCTS. PLEASE SEE TERMS AND CONDITIONS FOR MORE INFORMATION."
    }       
];
export default Shipping;
    